package com.najmi.sprint.core.domain.model

import kotlinx.datetime.LocalDate
import kotlinx.serialization.Serializable

/**
 * A weekly AI-generated retrospective entry.
 *
 * Generated by the actor-critic agent pair:
 * - Actor drafts the retro text (time distribution, context-switching, flagged concerns)
 * - Critic fact-checks against raw aggregates before display
 *
 * [promptVersion] enables correlation of retro quality with prompt iterations.
 */
@Serializable
data class RetroEntry(
    val id: String,
    val weekOf: LocalDate,
    val summaryText: String,
    val flaggedContextId: String? = null,
    val generatedByModel: String,
    val promptVersion: String,
    val criticApproved: Boolean
)
